#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1     

# Source tutorial run functions                   
. $WM_PROJECT_DIR/bin/tools/RunFunctions	

decomposePar -latestTime
mpirun -n `getNumberOfProcessors` `getApplication` -parallel | tee log.solver		
reconstructPar -latestTime

