#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean hyDbns
wclean myDbns_ext
wclean hyLusgsFoam
wclean myLusgsFoam

# ----------------------------------------------------------------- end-of-file
