#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake libso hyDbns
wmake libso myDbns_ext
wmake hyLusgsFoam
wmake myLusgsFoam

# ----------------------------------------------------------------- end-of-file
